version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitProjectPullTestProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newgitprojectpulltest.integrations:Test1
  packages:
  - name: NewGitProjectPullTestProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2026
